# Generated by Django 5.2.1 on 2026-05-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqms', '0004_validstudent_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='allowed_years',
            field=models.CharField(blank=True, default='', help_text='Comma-separated allowed years, e.g. 1,2,3,4', max_length=20),
        ),
    ]
