# Generated by Django 5.2.1 on 2026-06-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqms', '0006_alter_queueentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='current_ticket_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
