# Generated by Django 5.2.1 on 2026-06-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqms', '0008_queue_auto_mode_interval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queue',
            old_name='auto_mode',
            new_name='is_auto_mode_enabled',
        ),
        migrations.AddField(
            model_name='queue',
            name='last_auto_served_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='auto_serve_interval',
            field=models.PositiveIntegerField(default=0, help_text='Auto serve interval in minutes'),
        ),
    ]
