# Generated by Django 5.2.1 on 2026-06-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqms', '0009_rename_auto_mode_queue_is_auto_mode_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='estimated_time',
            field=models.PositiveIntegerField(default=5, help_text='Estimated service time in minutes'),
        ),
    ]
