# Generated by Django 5.2.1 on 2026-06-02 14:37

from django.db import migrations, models


def populate_ticket_numbers_and_migrate_status(apps, schema_editor):
    QueueEntry = apps.get_model('sqms', 'QueueEntry')
    for entry in QueueEntry.objects.all():
        if entry.status == 'completed':
            entry.status = 'served'
        if not entry.ticket_number and entry.position is not None:
            entry.ticket_number = f"SC-{entry.position:03d}"
        entry.save()


def reverse_migrate_status(apps, schema_editor):
    QueueEntry = apps.get_model('sqms', 'QueueEntry')
    for entry in QueueEntry.objects.all():
        if entry.status == 'served':
            entry.status = 'completed'
        if entry.ticket_number and entry.position is not None:
            entry.ticket_number = f"SC-{entry.position:03d}"
        entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ('sqms', '0010_alter_service_estimated_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueentry',
            name='ticket_number',
            field=models.CharField(blank=True, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('serving', 'Serving'), ('served', 'Served'), ('skipped', 'Skipped')], default='waiting', max_length=20),
        ),
        migrations.RunPython(populate_ticket_numbers_and_migrate_status, reverse_migrate_status),
    ]
