# Generated by Django 5.2.1 on 2026-06-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqms', '0013_notificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile_pictures/'),
        ),
    ]
