# Generated by Django 5.2.1 on 2026-05-04 13:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_customer_queue_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('serving', 'Serving'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='waiting', max_length=20),
        ),
    ]
