# Generated by Django 5.2.1 on 2026-05-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_queue_allowed_years'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queueentry',
            options={'ordering': ['position'], 'verbose_name': 'Queue Entry', 'verbose_name_plural': 'Queue Entries'},
        ),
        migrations.RemoveField(
            model_name='queueentry',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='validstudent',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='validstudent',
            name='registration_number',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
